select OWNER, TABLE_NAME, TABLESPACE_NAME from all_tables where TABLESPACE_NAME = 'PSAPSR3USR';


set linesize 999
col name for a45
select FILE#,STATUS,ENABLED,NAME, CREATE_BYTES/1024./1024. CREATE_BYTES_MB, BYTES/1024./1024. BYTES_MB from v$datafile
order by file#;

select TABLESPACE_NAME,INITIAL_EXTENT,MIN_EXTENTS,MAX_EXTENTS,PCT_INCREASE,STATUS,ALLOCATION_TYPE from dba_tablespaces;
select tablespace_name ts
     , FILE_NAME
     , sum(bytes)/1024./1024. "Total(MB)"
 from dba_data_files ddf
group by DDF.TABLESPACE_NAME, DDF.FILE_NAME
order by DDF.TABLESPACE_NAME, DDF.FILE_NAME;

-- espaço por datafile
set linesize 200
col TS for a15
col FILE_NAME for a45
compute sum of "Total(GB)" on report
compute sum of "Used(GB)" on report
compute sum of "Free(GB)" on report
compute count of FILE_NAME on report
break on report 
select TABLESPACE_NAME TS
     , FILE_NAME
     , SUM(DDF.BYTES)/1024./1024./1024. "Total(GB)"
     , ROUND((SUM(DDF.BYTES) - SUM(NVL(DFS.BYTES,0)))/1024./1024./1024.,1) "Used(GB)"
     , round(sum(nvl(dfs.bytes,0))/1024/1024,1) "Free(GB)"
from DBA_DATA_FILES DDF
full outer join (select DFS.file_id, sum(nvl(DFS.bytes,0)) bytes from SYS.DBA_FREE_SPACE DFS group by DFS.file_id) DFS on dfs.file_id = ddf.file_id
--where DDF.TABLESPACE_NAME not in ('SYSAUX','SYSTEM')
group by DDF.TABLESPACE_NAME, DDF.FILE_NAME
union all
select DDF.TABLESPACE_NAME TS
     , FILE_NAME
     , SUM(DDF.BYTES)/1024./1024./1024. "Total(GB)"
     , ROUND((SUM(DDF.BYTES) - SUM(NVL(DFS.BYTES,0)))/1024./1024./1024.,1) "Used(GB)"
     , ROUND(SUM(NVL(DFS.BYTES,0))/1024/1024,1) "Free(MB)"
from DBA_TEMP_FILES DDF
full outer join (select DFS.TABLESPACE_NAME, SUM(DFS.FREE_SPACE) BYTES from SYS.DBA_TEMP_FREE_SPACE DFS group by DFS.TABLESPACE_NAME) DFS on DFS.TABLESPACE_NAME = DDF.TABLESPACE_NAME
group by DDF.TABLESPACE_NAME, DDF.FILE_NAME
order by ts, FILE_NAME;


col FILE_NAME for a45
select   DDF.TABLESPACE_NAME "TablespaceName"
         --, DDF.FILE_NAME
         , SUM(DDF.BYTES)/1024./1024./1024. "Total(GB)"
         , ROUND((SUM(DDF.BYTES) - SUM(NVL(DFS.BYTES,0)))/1024./1024./1024.,1) "Used(GB)"
         , round(sum(nvl(dfs.bytes,0))/1024/1024/1024,1) "Free(GB)"
from SYS.DBA_DATA_FILES DDF
full outer join (select DFS.file_id, sum(DFS.bytes) bytes from SYS.DBA_FREE_SPACE DFS group by DFS.file_id) DFS on dfs.file_id = ddf.file_id
group by ddf.tablespace_name--, ddf.file_name
order by DDF.TABLESPACE_NAME--, DDF.FILE_NAME
;

-- verifica utilização da temp
SELECT   A.tablespace_name tablespace, D.mb_total,
         SUM (A.used_blocks * D.block_size) / 1024 / 1024 mb_used,
         D.mb_total - SUM (A.used_blocks * D.block_size) / 1024 / 1024 mb_free
FROM     v$sort_segment A,
         (
         SELECT   B.name, C.block_size, SUM (C.bytes) / 1024 / 1024 mb_total
         FROM     v$tablespace B, v$tempfile C
         WHERE    B.ts#= C.ts#
         GROUP BY B.name, C.block_size
         ) D
WHERE    A.tablespace_name = D.name
GROUP by A.tablespace_name, D.mb_total;

select s.osuser, s.process, s.username, s.serial#,
       sum(u.blocks)*vp.value/1024 sort_size
from   sys.v_$session s, sys.v_$sort_usage u, sys.v_$parameter vp
where  s.saddr = u.session_addr
  and  vp.name = 'db_block_size'
  and  s.osuser like '&1'
group  by s.osuser, s.process, s.username, s.serial#, vp.value
/



create pfile from spfile=/oracle/ED0/11204/dbs/spfileED0.2.ora;

alter system set control_files = '+DATA/ED0A/cntrlED0.dbf, +ARCH/ED0A/cntrled0.dbf' scope=spfile;
alter system set control_files = '+DATA/ed0a/cntrled0.dbf, +ARCH/ed0a/cntrled0.dbf' scope=spfile;

rmalias +data/ED0/cntrlED0.dbf
mkalias +DATA/ED0/CONTROLFILE/Current.256.936114003 +data/ED0A/cntrlED0.dbf
rmalias +ARCH/ED0/cntrlED0.dbf
mkalias +ARCH/ED0/CONTROLFILE/Current.256.936114003 +ARCH/ED0A/cntrlED0.dbf


ALTER TABLESPACE PSAPSR3731 RENAME TO PSAPSR3701;
ALTER TABLESPACE PSAPSR3701 RENAME TO PSAPSR3731;

ALTER TABLESPACE PSAPSR3701 OFFLINE NORMAL;
ALTER TABLESPACE PSAPSR3701 ONLINE;
ALTER TABLESPACE PSAPSR3701 RENAME DATAFILE '+DATA/ep0/datafile/psapsr3731.269.950552575' to '+DATA/ep0/datafile/psapsr3701.269.950552575'
ALTER TABLESPACE PSAPSR3701 drop datafile '+DATA/ep0/datafile/psapsr3731.270.950826801'

ALTER TABLESPACE PSAPSR3USR ONLINE;
ALTER TABLESPACE PSAPSR3USR OFFLINE NORMAL;
ALTER TABLESPACE PSAPSR3USR ADD DATAFILE '+DATA' SIZE 1G AUTOEXTEND OFF NEXT;
ALTER TABLESPACE PSAPSR3USR RENAME DATAFILE '+DATA/ep0/datafile/psapsr3usr.271.950826809' to '+DATA/EP0B/datafile/psapsr3usr.271.950826809';
ALTER DATABASE RENAME FILE '+DATA/ep0/datafile/psapsr3usr.271.950826809' to '+DATA/EP0B/datafile/psapsr3usr';

cp /mnt_hades/dump/psapsr3usr.271.950826809 +DATA/ep0b/datafile/psapsr3usr

ALTER TABLESPACE PSAPSR3701 ADD DATAFILE 
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF;
;

ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3731.269.950826793' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3701.270.952166727' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3701.319.952166771' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3701.320.952166399' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3701.321.952166805' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3731.269.950552575' resize 10G;
ALTER DATABASE DATAFILE '+DATA/ep0/datafile/psapsr3731.269.950552575' resize 10G;
ALTER TABLESPACE SYSAUX ADD DATAFILE '+DATA' size 10G;


DROP TABLESPACE PSAPSR3701 including contents;
CREATE TABLESPACE PSAPSR3701 DATAFILE '+DATA' size 10G;
ALTER TABLESPACE PSAPSR3701 ADD DATAFILE 
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF,
'+DATA' SIZE 10G AUTOEXTEND OFF;
;

DROP TABLESPACE PSAPSR3 including contents;
CREATE TABLESPACE PSAPSR3 DATAFILE '+DATA' size 30G;
ALTER TABLESPACE PSAPSR3 ADD DATAFILE '+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF,
'+DATA' SIZE 30G AUTOEXTEND OFF
;

drop TABLESPACE PSAPTEMP;
CREATE TABLESPACE PSAPTEMP DATAFILE '+DATA' size 20G;

ALTER DATABASE TEMPFILE '+DATA/ep0/tempfile/psaptemp.264.950826139' resize 31G;
ALTER DATABASE TEMPFILE '+DATA/ed0b/tempfile/psaptemp.279.943712623' resize 21G;
ALTER tablespace PSAPTEMP ADD TEMPFILE '+DATA' size 31G;

ALTER tablespace PSAPTEMP drop tempfile '+DATA/ed0a/tempfile/psaptemp.335.952796805';

ALTER TABLESPACE undotbs_01
     ADD DATAFILE '/u01/oracle/rbdb1/undo0102.dbf' AUTOEXTEND ON NEXT 1M 
         MAXSIZE UNLIMITED;

CREATE UNDO TABLESPACE PSAPUNDO2 DATAFILE '+DATA' SIZE 1G REUSE AUTOEXTEND ON;
ALTER SYSTEM SET UNDO_TABLESPACE = PSAPUNDO2
DROP TABLESPACE PSAPUNDO
CREATE UNDO TABLESPACE PSAPUNDO DATAFILE '+DATA' SIZE 1G REUSE AUTOEXTEND ON;
ALTER SYSTEM SET UNDO_TABLESPACE = PSAPUNDO
DROP TABLESPACE PSAPUNDO2

ALTER TABLESPACE PSAPUNDO DROP DATAFILE '+DATA/ep0/datafile/psapundo.263.950826139';
ALTER TABLESPACE PSAPUNDO ADD DATAFILE '+DATA' SIZE 6G REUSE AUTOEXTEND ON;

